### ISSUE TITLE
Difference between number of tracks fetched and # of possible annotations reported

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/deepsea-ai#15]
@danellecline I'm fetching the events from M3_EVENT_TRACKS database and grouping them as tracks in my app. 

I'm seeing a difference between the number of tracks and the number of possible annotations reported in your dashboard. For example, media 93 (D1371_20210801T154045Z_h264.mp4) has 66 tracks but the dashboard says there are 38 possible annotations and I'm wondering why they're different. Are you applying a filter based on confidence or some other criteria? Thanks

ref: mbari-org/vars-feedback#37

**Comment by danellecline** [comment]
@hohonuuli The dashboard reports the database track view, which represents the "best" track which is the concept with the maximum confidence sum over the lifetime of the track.  This is reported as the max_concept.    
 
You should get 38 tracks with the  query 

```query {
  tracks(where: {
    ,media_id: {
      equals: 93
    }
  })
  {
    track_uuid
   max_concept
  }
}
```

**Comment by danellecline** [comment]
You can fetch the tracks and events with 

```
query fullTracksByMediaId {
  tracks(where: {media_id: {equals: 44}}, take: 10, skip: 10) {
    track_uuid
    max_concept
    max_confidence
    start_frame_number
    end_frame_number
    events {
      uuid
      x
      y
      width
      height
      frame_num
    }
  }
}
```

**Comment by danellecline** [comment]
Here is the track view in case that's helpful.  I noticed in previewing the output in the dashboard in early testing that this produced better results than simply choosing the concept with the maximum concept - that can be wrong, i.e. the models can be confidently wrong.  This is designed to return the best concept as the one with the maximum confidence sum at the earliest frame. Is there an error in this that is causing the discrepancy in the track counts?

```
create view "Track"
            (track_uuid, media_id, max_concept, confidence_sum, start_frame_number, end_frame_number,
             max_surprise, max_confidence, event_count, approved_count)
as
SELECT t2.track_uuid,
       t2.media_id,
       t2.max_concept,
       t2.confidence_sum,
       t2.start_frame_number,
       t2.end_frame_number,
       t2.max_surprise,
       t2.max_confidence,
       t2.event_count,
       t2.approved_count
FROM (SELECT e.track_uuid,
             e.media_id,
             max(e.confidence_sum) + min(e.frame_num) AS best_track
      FROM "Event" e
               RIGHT JOIN "Media" m ON e.media_id = m.id
      GROUP BY e.track_uuid, e.media_id) q1
         JOIN (SELECT e.track_uuid,
                      e.media_id,
                      e.concept         AS max_concept,
                      e.confidence_sum,
                      count(*)          AS event_count,
                      sum(CASE WHEN e.approved = 1 THEN 1 ELSE 0 END)  AS approved_count,
                      min(e.frame_num)  AS start_frame_number,
                      max(e.frame_num)  AS end_frame_number,
                      max(e.surprise)   AS max_surprise,
                      max(e.confidence) AS max_confidence
               FROM "Event" e
                        RIGHT JOIN "Media" m ON e.media_id = m.id
               GROUP BY e.track_uuid, e.media_id, e.concept, e.confidence_sum) t2
              ON q1.track_uuid = t2.track_uuid AND q1.best_track = (t2.confidence_sum + t2.start_frame_number);

```

**Comment by hohonuuli** [comment]
@danellecline Thanks for the response. For a sanity check, if I run the SQL below, it returns 66 track_uuids for media_id 93. Why is the view returning 38 tracks instead of 66??

```sql
SELECT 
    COUNT(DISTINCT track_uuid)
FROM
    Event
WHERE
    media_id = 93
```

**Comment by danellecline** [comment]
@hohonuuli I don't think you are missing anything.  I suspect there is a bug in the Track View logic.  I'll look into this more to investigate tomorrow. Still on vacation now.
   
There may be cases where there isn't a distinct winner in the track view, e.g. a tie or a null condition that is not handled or something along those lines.

**Comment by hohonuuli** [comment]
@danellecline No rush. I have a work around for now. Enjoy your vacation and we can chat about it when you get back.

**Comment by danellecline** [comment]
This issue has been resolved in the database. See https://github.com/mbari-org/deepsea-ai-backend/issues/28 for details.
